import Providers from '@/views/provider'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/views/layout/footer'
import Headers from '@/views/layout/header'
import { Toaster } from 'react-hot-toast'
import { ClerkProvider } from '@clerk/nextjs'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="">
          <ClerkProvider>
            <Providers>
              <Headers />
              {children}
              <Toaster position="top-right" />
              <Footer />
            </Providers>
          </ClerkProvider>

        </main>
      </body>
    </html>
  )
}
